// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhcuyswqwlsbpvwyyqds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoY3V5c3dxd2xzYnB2d3l5cWRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNzQzMTQsImV4cCI6MjA3Mjk1MDMxNH0.csoUhEHtPujHGYBr3r31bB7sVdKN-WDODEy1acxyx-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});